[main]
# files needed for adnebulae to run - shouldn't be changing much
files = "/usr/share/adnebulae"
# config directory. filepaths will be relative to this
confbase = "/etc/adnebulae"
listen = ":8080"
ssl = true
sslkey = "server.key"
sslcrt = "server.crt"

[openstack]
auth-url = "http://cloudman.cecsresearch.org:5000/v2.0"

[chef]
server-url = "https://216.249.138.190:443"
# validator-key = "validation.pem"
# validator-name = "chef-validator"
# client-config = "client.rb.templ"
